###
GET  http://localhost:3000/products

###
POST http://localhost:3000/user
Content-Type: application/json

{
   "age": 34
}

###
POST  http://localhost:3000/login
Content-Type: application/json

{
    "name": "sdas",
    "email": "sdas@example.com"

}