###
GET  http://localhost:3000/products

###
POST http://localhost:3000/user
Content-Type: application/json

{
   "age": 34
}

###
POST  http://localhost:3000/signup
Content-Type: application/json

{
    "name": "roshan",
    "email": "alfredRoshan@example.com",
    "password" :"Newpassword"

}